In [1]:
pip install numpy

In [2]:
import numpy as np

1. Perform arithmetic operations on NumPy arrays.

In [4]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]


2. Write a script to compute the mean and standard deviation of a NumPy array.

In [5]:
m = np.mean(a)
s = np.std(a)
print(m)
print(s)

2.0
0.816496580927726


3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [9]:
s = np.arange(10,51,5)
print(s)

[10 15 20 25 30 35 40 45 50]


4. Reshape the array into a 2x4 matrix.

In [14]:
r = np.array([1,2,3,4,5,6,7,8])
r = r.reshape(2,4)
print(r)

[[1 2 3 4]
 [5 6 7 8]]


5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1: ,0:2])
arr[arr>4]=0
print(arr)

[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


6. Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division.

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a*b)
print(a/b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.

In [36]:
x = np.array((4,4))
n = np.random.randint(1,6,x)
print(n)
print(np.mean(n,axis=0))
print(np.max(n))
print(np.sum(n))

[[4 5 4 3]
 [1 1 4 2]
 [4 5 5 4]
 [5 1 1 5]]
[3.5 3.  3.5 3.5]
5
54


8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [37]:
arr = np.array([1, 2, 3, 4])
arr+=10
arr*=2
print(arr)

[22 24 26 28]


9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.

In [51]:
e = np.random.randint(1,101,(3,4,5))
print(e)
print('........................')
print(e[1])
print('........................')
print(e[:,:2,2:])
print('........................')
e[e%3==0]=-1
print(e)

[[[ 69   1  15  98  70]
  [ 45  39  56  93  53]
  [ 36  88  98  77  89]
  [ 88  55  39  25  97]]

 [[ 11 100  65  72  79]
  [  7  81  18  29  21]
  [ 24  70  47  94  30]
  [ 50  28  45  79  76]]

 [[ 34  90  88  93  41]
  [ 45  10  65  85  68]
  [  2  81  40  27 100]
  [ 59  65  35  86  20]]]
........................
[[ 11 100  65  72  79]
 [  7  81  18  29  21]
 [ 24  70  47  94  30]
 [ 50  28  45  79  76]]
........................
[[[15 98 70]
  [56 93 53]]

 [[65 72 79]
  [18 29 21]]

 [[88 93 41]
  [65 85 68]]]
........................
[[[ -1   1  -1  98  70]
  [ -1  -1  56  -1  53]
  [ -1  88  98  77  89]
  [ 88  55  -1  25  97]]

 [[ 11 100  65  -1  79]
  [  7  -1  -1  29  -1]
  [ -1  70  47  94  -1]
  [ 50  28  -1  79  76]]

 [[ 34  -1  88  -1  41]
  [ -1  10  65  85  68]
  [  2  -1  40  -1 100]
  [ 59  65  35  86  20]]]


10. Work with broadcasting and advanced operations in NumPy.
Create a NumPy array arr of shape (3, 3) with random integers between  
1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array.

In [59]:
y = np.random.randint(1,21,(3,3))
print(y)

q = y-np.mean(y,axis=1)
print(q)

print(np.square(y))

flat =


[[11 14  9]
 [ 7 10 13]
 [15  7  4]]
[[-0.33333333  4.          0.33333333]
 [-4.33333333  0.          4.33333333]
 [ 3.66666667 -3.         -4.66666667]]
[[121 196  81]
 [ 49 100 169]
 [225  49  16]]
