In [ ]:
pip install numpy

In [2]:
import numpy as np

1. Perform arithmetic operations on NumPy arrays.

In [ ]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]


2. Write a script to compute the mean and standard deviation of a NumPy array.

In [ ]:
m = np.mean(a)
s = np.std(a)
print(m)
print(s)

2.0
0.816496580927726


3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:
s = np.arange(10,51,5)
print(s)

[10 15 20 25 30 35 40 45 50]


4. Reshape the array into a 2x4 matrix.

In [ ]:
r = np.array([1,2,3,4,5,6,7,8])
r = r.reshape(2,4)
print(r)

[[1 2 3 4]
 [5 6 7 8]]


5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1: ,0:2])
arr[arr>4]=0
print(arr)

[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


6. Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a*b)
print(a/b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.

In [ ]:
x = np.array((4,4))
n = np.random.randint(1,6,x)
print(n)
print(np.mean(n,axis=0))
print(np.max(n))
print(np.sum(n))

[[4 5 4 3]
 [1 1 4 2]
 [4 5 5 4]
 [5 1 1 5]]
[3.5 3.  3.5 3.5]
5
54


8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [ ]:
arr = np.array([1, 2, 3, 4])
arr+=10
arr*=2
print(arr)

[22 24 26 28]


9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.

In [3]:
e = np.random.randint(1,101,(3,4,5))
print(e)
print('........................')
print(e[1])
print('........................')
print(e[:,0:2,-3:])
print('........................')
e[e%3==0]=-1
print(e)

[[[49 93 33 93 96]
  [20 91 31 96 18]
  [79 64  7 75 28]
  [32 48 19 86  3]]

 [[ 4 12 17 14 80]
  [60 27 29 85 65]
  [37 23 39 46 38]
  [42 49 63 31 25]]

 [[37 84 23 23 47]
  [82 27 72  6 87]
  [74 38  4 83 30]
  [79 98 50 79 15]]]
........................
[[ 4 12 17 14 80]
 [60 27 29 85 65]
 [37 23 39 46 38]
 [42 49 63 31 25]]
........................
[[[33 93 96]
  [31 96 18]]

 [[17 14 80]
  [29 85 65]]

 [[23 23 47]
  [72  6 87]]]
........................
[[[49 -1 -1 -1 -1]
  [20 91 31 -1 -1]
  [79 64  7 -1 28]
  [32 -1 19 86 -1]]

 [[ 4 -1 17 14 80]
  [-1 -1 29 85 65]
  [37 23 -1 46 38]
  [-1 49 -1 31 25]]

 [[37 -1 23 23 47]
  [82 -1 -1 -1 -1]
  [74 38  4 83 -1]
  [79 98 50 79 -1]]]


10. Work with broadcasting and advanced operations in NumPy.
Create a NumPy array arr of shape (3, 3) with random integers between  
1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array.

In [10]:
n = np.random.randint(1,21,(3,3))
print(n)
print("---------- ")
for i in range(3):
  n[i] = n[i]-np.mean(n[i])
print("Normalisation :\n",n)
print("---------- ")
print("Squared array :\n",np.square(n))
print("---------- ")
f = n.flatten()
t = np.argsort(f)[-3:]
row,col = np.unravel_index(t,n.shape)
print("Indices of top 3 maximum values :\n",list(zip(row,col)))

[[ 2  3  6]
 [12  2 15]
 [11 18 18]]
---------- 
Normalisation :
 [[-1  0  2]
 [ 2 -7  5]
 [-4  2  2]]
---------- 
Squared array :
 [[ 1  0  4]
 [ 4 49 25]
 [16  4  4]]
---------- 
Indices of top 3 maximum values :
 [(2, 1), (2, 2), (1, 2)]
